export const EconomyConfig = {
    // Normal items available for random rotation
    buyPoolNormal: {
        "minecraft:bread": 2500,
        "minecraft:cooked_beef": 5000,
        "minecraft:cooked_porkchop": 5000,
        "minecraft:cooked_mutton": 5000,
        "minecraft:cooked_chicken": 4500,
        "minecraft:cooked_rabbit": 6000,
        "minecraft:cooked_cod": 3500,
        "minecraft:cooked_salmon": 4000,
        "minecraft:golden_apple": 75000,
        "minecraft:golden_carrot": 35000,
        "minecraft:pumpkin_pie": 6000,
        "minecraft:mushroom_stew": 3000,
        "minecraft:rabbit_stew": 7000,

        // Blok Kayu (Logs)
        "minecraft:oak_log": 3500,
        "minecraft:spruce_log": 3500,
        "minecraft:birch_log": 3500,
        "minecraft:jungle_log": 3500,
        "minecraft:acacia_log": 3500,
        "minecraft:dark_oak_log": 3500,
        "minecraft:mangrove_log": 4000,
        "minecraft:cherry_log": 4500,

        // Bibit Pohon (Saplings)
        "minecraft:oak_sapling": 5000,
        "minecraft:spruce_sapling": 5000,
        "minecraft:birch_sapling": 5000,
        "minecraft:jungle_sapling": 5000,
        "minecraft:acacia_sapling": 5000,
        "minecraft:dark_oak_sapling": 5000,
        "minecraft:mangrove_propagule": 6000,
        "minecraft:cherry_sapling": 7000,

        // Pertanian
        "minecraft:wheat_seeds": 500,
        "minecraft:pumpkin_seeds": 800,
        "minecraft:melon_seeds": 800,
        "minecraft:beetroot_seeds": 600,
        "minecraft:apple": 1500,
        "minecraft:carrot": 2000,
        "minecraft:potato": 2000,
        "minecraft:wheat": 2000,
        "minecraft:sugar_cane": 3000,
        "minecraft:bamboo": 1000,
        "minecraft:sweet_berries": 1000,
        "minecraft:glow_berries": 2500,
        "minecraft:kelp": 500,
        "minecraft:cocoa_beans": 1500,
        "minecraft:cactus": 2500,

        // Tambang (Ores & Minerals)
        "minecraft:coal": 2000,
        "minecraft:iron_ingot": 8000,
        "minecraft:gold_ingot": 12000,
        "minecraft:copper_ingot": 3000,
        "minecraft:redstone": 3000,
        "minecraft:lapis_lazuli": 4000,
        "minecraft:diamond": 50000,
        "minecraft:emerald": 25000,
        "minecraft:quartz": 3000,
        "minecraft:amethyst_shard": 5000,

        // Blok Pembangunan Dasar
        "minecraft:cobblestone": 200,
        "minecraft:stone": 500,
        "minecraft:smooth_stone": 800,
        "minecraft:granite": 400,
        "minecraft:diorite": 400,
        "minecraft:andesite": 400,
        "minecraft:calcite": 1000,
        "minecraft:tuff": 600,
        "minecraft:deepslate": 600,
        "minecraft:dirt": 100,
        "minecraft:sand": 200,
        "minecraft:red_sand": 500,
        "minecraft:gravel": 250,
        "minecraft:glass": 800,
        "minecraft:obsidian": 8000,
        "minecraft:crying_obsidian": 15000,
        "minecraft:glowstone": 10000,
        "minecraft:sea_lantern": 15000,
        "minecraft:prismarine": 4000,
        "minecraft:bricks": 2000,

        // Dekorasi & Utilities
        "minecraft:torch": 500,
        "minecraft:lantern": 2500,
        "minecraft:soul_lantern": 3500,
        "minecraft:chest": 1000,
        "minecraft:ender_chest": 250000,
        "minecraft:anvil": 150000,
        "minecraft:enchanting_table": 250000,
        "minecraft:brewing_stand": 50000,
        "minecraft:bookshelf": 5000,
        "minecraft:bed": 4000,
        "minecraft:scaffolding": 500,
        "minecraft:jukebox": 150000,
        "minecraft:note_block": 25000,
        "minecraft:shroomlight": 12000,
        "minecraft:end_rod": 25000,
        "minecraft:campfire": 5000,
        "minecraft:soul_campfire": 8000,
        "minecraft:bell": 50000,
        "minecraft:barrel": 1500,
        "minecraft:composter": 1500,
        "minecraft:loom": 2000,
        "minecraft:stonecutter": 2000,
        "minecraft:grindstone": 2500,
        "minecraft:smithing_table": 5000,
        "minecraft:cartography_table": 2500,
        "minecraft:fletching_table": 2000,
        "minecraft:cauldron": 8000,

        // Mob Drops & Materials
        "minecraft:string": 1000,
        "minecraft:leather": 2000,
        "minecraft:feather": 1000,
        "minecraft:rotten_flesh": 500,
        "minecraft:bone": 1000,
        "minecraft:spider_eye": 2000,
        "minecraft:gunpowder": 3000,
        "minecraft:slime_ball": 5000,
        "minecraft:magma_cream": 6000,
        "minecraft:ghast_tear": 25000,
        "minecraft:ender_pearl": 15000,
        "minecraft:blaze_rod": 20000,
        "minecraft:phantom_membrane": 10000,
        "minecraft:shulker_shell": 50000,
        "minecraft:bone_block": 5000,
        "minecraft:spider_web": 8000,
        "minecraft:ender_eye": 25000,
        "minecraft:honeycomb": 3000,
        "minecraft:honey_block": 10000,
        "minecraft:scute": 20000,
        "minecraft:turtle_helmet": 75000,
        "minecraft:nautilus_shell": 50000,

        // Bibit & Makhluk (Steril)
        "minecraft:cow_spawn_egg": 50000,
        "minecraft:pig_spawn_egg": 40000,
        "minecraft:sheep_spawn_egg": 45000,
        "minecraft:chicken_spawn_egg": 30000,
        "minecraft:horse_spawn_egg": 80000,
        "minecraft:villager_spawn_egg": 150000,
        "minecraft:zombie_spawn_egg": 25000,
        "minecraft:skeleton_spawn_egg": 30000,
        "minecraft:creeper_spawn_egg": 50000,
        "minecraft:slime_spawn_egg": 60000,
        "minecraft:spider_spawn_egg": 30000,
        "minecraft:enderman_spawn_egg": 75000,

        // Misc & Petualangan
        "minecraft:arrow": 1000,
        "minecraft:bow": 5000,
        "minecraft:crossbow": 8000,
        "minecraft:shield": 10000,
        "minecraft:experience_bottle": 10000,
        "minecraft:name_tag": 50000,
        "minecraft:saddle": 75000,
        "minecraft:lead": 5000,
        "minecraft:clock": 15000,
        "minecraft:compass": 10000,
        "minecraft:spyglass": 25000,
        "minecraft:bucket": 5000,
        "minecraft:water_bucket": 10000,
        "minecraft:lava_bucket": 15000,

        // Blok Nether & End
        "minecraft:netherrack": 100,
        "minecraft:soul_sand": 3000,
        "minecraft:soul_soil": 3000,
        "minecraft:magma_block": 4000,
        "minecraft:basalt": 1000,
        "minecraft:blackstone": 1000,
        "minecraft:end_stone": 2000,
        "minecraft:purpur_block": 5000,

        // Redstone & Mekanik
        "minecraft:slime": 50000,
        "minecraft:piston": 25000,
        "minecraft:sticky_piston": 75000,
        "minecraft:hopper": 60000,
        "minecraft:dispenser": 30000,
        "minecraft:observer": 45000,
        "minecraft:iron_block": 75000,
        "minecraft:gold_block": 110000,
        "minecraft:dropper": 25000,
        "minecraft:comparator": 35000,
        "minecraft:repeater": 20000,
        "minecraft:daylight_detector": 40000,
        "minecraft:target": 15000,
        "minecraft:lightning_rod": 10000,
        "minecraft:redstone_lamp": 12000,
        "minecraft:tripwire_hook": 5000
    },
    // OP items with insane prices
    buyPoolOP: {
        "minecraft:enchanted_golden_apple": 1000000,
        "minecraft:elytra": 5000000,
        "minecraft:nether_star": 2000000,
        "minecraft:totem_of_undying": 500000,
        "minecraft:beacon": 3000000,
        "minecraft:shulker_box": 750000,
        "minecraft:diamond_block": 500000,
        "minecraft:emerald_block": 250000,
        "minecraft:netherite_ingot": 1200000,
        "minecraft:netherite_block": 11000000,
        "minecraft:dragon_breath": 800000,
        "minecraft:heart_of_the_sea": 600000,
        "minecraft:conduit": 1500000,
        "minecraft:trident": 2500000,
        "minecraft:sponge": 150000,
        "minecraft:dragon_egg": 10000000,
        "minecraft:wither_skeleton_skull": 450000,
        "minecraft:recovery_compass": 850000,
        "minecraft:echo_shard": 150000,
        "minecraft:heavy_core": 3500000,
        "minecraft:mace": 5000000
    },
    sellPrices: {
        // Pertanian & Alam (Farming & Nature) - RE-BUFFED FOR EARLY GAME
        "minecraft:wheat": 150,
        "minecraft:potato": 120,
        "minecraft:carrot": 120,
        "minecraft:beetroot": 150,
        "minecraft:melon_slice": 80,
        "minecraft:pumpkin": 200,
        "minecraft:sugar_cane": 100,
        "minecraft:bamboo": 50,
        "minecraft:apple": 300,
        "minecraft:sweet_berries": 50,
        "minecraft:glow_berries": 150,
        "minecraft:kelp": 40,
        "minecraft:cocoa_beans": 200,
        "minecraft:cactus": 100,
        "minecraft:brown_mushroom": 150,
        "minecraft:red_mushroom": 150,
        "minecraft:nether_wart": 400,
        "minecraft:chorus_fruit": 600,
        "minecraft:oak_log": 250,
        "minecraft:spruce_log": 250,
        "minecraft:birch_log": 250,
        "minecraft:jungle_log": 250,
        "minecraft:acacia_log": 250,
        "minecraft:dark_oak_log": 250,
        "minecraft:cherry_log": 350,
        "minecraft:mangrove_log": 350,

        // Hasil Tambang (Ores & Mining) - RE-BUFFED
        "minecraft:coal": 150,
        "minecraft:raw_iron": 300,
        "minecraft:iron_ingot": 500,
        "minecraft:raw_copper": 150,
        "minecraft:copper_ingot": 250,
        "minecraft:raw_gold": 800,
        "minecraft:gold_ingot": 1200,
        "minecraft:lapis_lazuli": 200,
        "minecraft:redstone": 150,
        "minecraft:diamond": 10000,
        "minecraft:emerald": 1500,
        "minecraft:amethyst_shard": 450,
        "minecraft:quartz": 200,
        "minecraft:netherite_scrap": 50000,
        "minecraft:netherite_ingot": 250000,
        "minecraft:obsidian": 200,
        "minecraft:crying_obsidian": 400,

        // Mob Drops (Biasa & Langka) - NERFED BASE DROPS
        "minecraft:rotten_flesh": 2,
        "minecraft:bone": 5,
        "minecraft:string": 5,
        "minecraft:spider_eye": 10,
        "minecraft:gunpowder": 15,
        "minecraft:ender_pearl": 200,
        "minecraft:blaze_rod": 400,
        "minecraft:ghast_tear": 1000,
        "minecraft:magma_cream": 50,
        "minecraft:slime_ball": 40,
        "minecraft:phantom_membrane": 250,
        "minecraft:shulker_shell": 3000,
        "minecraft:wither_skeleton_skull": 15000,
        "minecraft:nether_star": 250000,
        "minecraft:dragon_egg": 1000000,
        "minecraft:leather": 15,
        "minecraft:feather": 5,
        "minecraft:rabbit_hide": 10,
        "minecraft:rabbit_foot": 150,
        "minecraft:scute": 500,
        "minecraft:turtle_helmet": 5000,
        "minecraft:nautilus_shell": 2000,
        "minecraft:heart_of_the_sea": 25000,
        "minecraft:sponge": 5000,

        // Bahan Bangunan & Alam (Blocks) - RE-BUFFED
        "minecraft:dirt": 10,
        "minecraft:cobblestone": 20,
        "minecraft:stone": 40,
        "minecraft:sand": 20,
        "minecraft:gravel": 20,
        "minecraft:glass": 80,
        "minecraft:clay_ball": 100,
        "minecraft:brick": 150,
        "minecraft:snowball": 10,
        "minecraft:ice": 150,
        "minecraft:packed_ice": 400,
        "minecraft:blue_ice": 1200,
        "minecraft:prismarine_shard": 250,
        "minecraft:prismarine_crystals": 300,
        "minecraft:glowstone_dust": 150,
        "minecraft:magma_block": 200,
        "minecraft:soul_sand": 150,
        "minecraft:soul_soil": 150,
        "minecraft:basalt": 50,
        "minecraft:blackstone": 50,

        // Item Makanan Olahan & Lainnya (Food & Misc)
        "minecraft:cooked_porkchop": 40,
        "minecraft:cooked_mutton": 40,
        "minecraft:cooked_chicken": 30,
        "minecraft:cooked_rabbit": 50,
        "minecraft:cooked_cod": 20,
        "minecraft:cooked_salmon": 30,
        "minecraft:golden_apple": 2500,
        "minecraft:enchanted_golden_apple": 150000,
        "minecraft:golden_carrot": 150,
        "minecraft:glistering_melon_slice": 150,
        "minecraft:honeycomb": 50,
        "minecraft:honey_bottle": 60,
        "minecraft:totem_of_undying": 10000, // Easily farmable from raids, severely nerfed
        "minecraft:experience_bottle": 100,
        "minecraft:name_tag": 500,
        "minecraft:saddle": 500,
        "minecraft:iron_horse_armor": 400,
        "minecraft:golden_horse_armor": 800,
        "minecraft:diamond_horse_armor": 5000,
        "minecraft:bell": 1000,
        "minecraft:lead": 50,
        "minecraft:compass": 200,
        "minecraft:recovery_compass": 5000,
        "minecraft:echo_shard": 1500
    }
};
